const countryConversion = {
    Malaysia: "🇲🇾",
    UAE: "🇦🇪",
    Germany: "🇩🇪",
    China: "🇨🇳",
    Austria: "🇦🇹",
    Sweden: "🇸🇪",
    India: "🇮🇳",
    Argentina: "🇦🇷",
    Switzerland: "🇨🇭",
    Qatar: "🇶🇦",
    Azerbaijan: "🇦🇿",
    Netherlands: "🇳🇱",
    UK: "🇬🇧",
    Mexico: "🇲🇽",
    Russia: "🇷🇺",
    Korea: "🇰🇷",
    Turkey: "🇹🇷",
    Monaco: "🇲🇨",
    Canada: "🇨🇦",
    Australia: "🇦🇺",
    Japan: "🇯🇵",
    USA: "🇺🇸",
    Italy: "🇮🇹",
    Hungary: "🇭🇺",
    Brazil: "🇧🇷",
    Morocco: "🇲🇦",
    "South Africa": "🇿🇦",
    Singapore: "🇸🇬",
    "Saudi Arabia": "🇸🇦",
    France: "🇫🇷",
    Bahrain: "🇧🇭",
    Belgium: "🇧🇪",
    Spain: "🇪🇸",
    Portugal: "🇵🇹",
};